name: 'K.Actions.NextVersion - Release-based Semantic Versioning'
description: 'Analyzes merged branches since last release to determine the next semantic version for PowerShell modules with Alpha/Beta support'
inputs:
  manifestPath:
    description: 'Path to the PowerShell module manifest (.psd1) file. Auto-discovery if empty.'
    required: false
    default: ''
  branchName:
    description: 'Current branch name for analysis. Uses github.ref_name if empty.'
    required: false
    default: ''
  targetBranch:
    description: 'Target branch for release analysis (main/master). Auto-discovery if empty.'
    required: false
    default: ''

outputs:
  currentVersion:
    description: 'The current version from the manifest file'
    value: ${{ steps.run-script.outputs.currentVersion }}
  bumpType:
    description: 'Detected version bump type (major/minor/patch/none)'
    value: ${{ steps.run-script.outputs.bumpType }}
  newVersion:
    description: 'The calculated new semantic version'
    value: ${{ steps.run-script.outputs.newVersion }}
  lastReleaseTag:
    description: 'The latest release tag found in the repository'
    value: ${{ steps.run-script.outputs.lastReleaseTag }}
  targetBranch:
    description: 'The target branch used for analysis'
    value: ${{ steps.run-script.outputs.targetBranch }}
  suffix:
    description: 'Alpha/Beta suffix if detected (alpha/beta/empty)'
    value: ${{ steps.run-script.outputs.suffix }}
  warning:
    description: 'Warning message if unusual version detected'
    value: ${{ steps.run-script.outputs.warning }}
  actionRequired:
    description: 'Whether manual action is required before proceeding (true/false)'
    value: ${{ steps.run-script.outputs.actionRequired }}
  actionInstructions:
    description: 'Detailed instructions for required manual action'
    value: ${{ steps.run-script.outputs.actionInstructions }}

runs:
  using: 'composite'
  steps:
    - id: run-script
      shell: pwsh
      run: |
        # Import the K.PSGallery.SemanticVersioning module
        Import-Module "$env:GITHUB_ACTION_PATH/K.PSGallery.SemanticVersioning" -Force
        
        # Call the main function with parameters
        $result = Get-NextSemanticVersion `
          -ManifestPath "${{ inputs.manifestPath }}" `
          -BranchName "${{ inputs.branchName }}" `
          -TargetBranch "${{ inputs.targetBranch }}"

        echo "currentVersion=$($result.CurrentVersion)" >> $env:GITHUB_OUTPUT
        echo "bumpType=$($result.BumpType)" >> $env:GITHUB_OUTPUT
        echo "newVersion=$($result.NewVersion)" >> $env:GITHUB_OUTPUT
        echo "lastReleaseTag=$($result.LastReleaseTag)" >> $env:GITHUB_OUTPUT
        echo "targetBranch=$($result.TargetBranch)" >> $env:GITHUB_OUTPUT
        echo "suffix=$($result.Suffix)" >> $env:GITHUB_OUTPUT
        echo "warning=$($result.Warning)" >> $env:GITHUB_OUTPUT
        echo "actionRequired=$($result.ActionRequired)" >> $env:GITHUB_OUTPUT
        echo "actionInstructions=$($result.ActionInstructions)" >> $env:GITHUB_OUTPUT